### ISSUE TITLE
Nullary operators defined in the REPL cannot be invoked

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1045]
```
$  quint
Quint REPL 0.12.0
Type ".exit" to exit, or ".help" for more information
>>> def f(x) = 1

>>> f(1)
1
>>> def g() = 1

>>> g()
static analysis error: error: [QNT000] Couldn't unify int and oper
Trying to unify int and () => t0

g()
^^^

static analysis error: error: [QNT000] Can't unify different types of effects
Trying to unify Pure and () => e0
Trying to infer effect for operator application in g()

g()
^^^

compile error: error: Expected g to be an operator
g()
^^^
```

**Comment by konnov** [comment]
@shonfeder what is your expectation here? If you type `g` without parentheses, it actually works, since `g` is a value, not an operator definition. I don't see a big issue in adding support for `g()`. In case of an impure definition, it even makes a bit of sense. In case of a `pure` definition, this may be confusing though.

**Comment by bugarela** [comment]
Closing in favor of https://github.com/informalsystems/quint/issues/881
