### ISSUE TITLE
Strange error location given type annotation

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1177]
Here is my spec: https://github.com/cosmos/interchain-security/blob/4f77d68b9ad06525aa7241f392e6754de364f90c/tests/difference/core/quint_model/ccv.qnt#L357

in v0.9.0 of the VSCode quint extension, I get red squigglies in line 357, under currentState.providerState.
The error message reads
```
Incompatible tails for rows with disjoint fields: {} and { | tail_t491 }
Trying to unify { consumerStatus: (Chain -> str), chainState: ChainState, outstandingPacketsToConsumer: (Chain -> List[VSCPacket]), receivedMaturations: Set[VSCMaturedPacket], sentVSCPackets: (Chain -> Set[VSCPacket]), vscSendTimestamps: ((Chain, VSCId) -> Timestamp), providerValidatorSetChangedInThisBlock: bool, runningVscId: int } and { providerState: t491 | tail_t491 }
```

I find the error location strange - the problem is on line 354, changing currentState to currentState.providerState fixes the problem, see this: https://github.com/cosmos/interchain-security/blob/fa233d655ff0a86073f47bdebe7fce5054b7c6b7/tests/difference/core/quint_model/ccv.qnt#L354

It feels like the red underline should be under currentState, or under isCurrentlyConsumer, but definitely on L354. Is this a bug?

**Comment by bugarela** [comment]
Interesting. What I believe is happening is: the fact that the types for `currentState` mismatch between lines 354 and 357 is being flagged before checking if both of them match the type signature. Unification for types happens for the nested definitions first, and only later will happen for the `recvPacketOnProvider` definition (that has the annotation), so that's why it's reported on line 357.

It's a usability bug, thanks for reporting!

**Comment by shonfeder** [comment]
I think this is the same issue that Jan raised last week, interfering with his work a bit.

**Comment by shonfeder** [comment]
Here's a relatively minimal example of the problem:

```scala
module t {
    pure def foo(s: int): int = {
      val x = s.map(y => y + 1)
      val y = s + 1
      y
    }
}
```

Which gives

```
$  quint typecheck t.qnt 
t.qnt:4:15 - error: [QNT000] Couldn't unify int and set
Trying to unify int and Set[int]
Trying to unify (int, int) => int and (Set[int], int) => _t4

4:       val y = s + 1
                 ^^^^^

error: typechecking failed
```

But we would, instead, expect that the error is flagged on line 3, given the type annotation on `s`.

**Comment by shonfeder** [comment]
I understand now why this is not easy to fix given our current type checking algorithm.

We want annotations of operator parameters to be added to the constraint store when we enter into the operators body, so that we can flag an error at the first occurrence of a conflicting type inference for one of the parameters.

But type annotations are only stored on the `QuintOpDef`

https://github.com/informalsystems/quint/blob/5d28bbe2ef97451269e4eb4852cee872bb5e3dc3/quint/src/ir/quintIr.ts#L258-L267

Whereas the parameters occur on the child `expr : QuintEx`, in case that is a lambda.

The current algorithm uses the visitor pattern to traverse the IR. When we enter a `QuintOpDef` we don't have access to the fresh type variables for the child `expr`, since those are only generated after we enter the `expr`. By the time we leave the top level `QuintOpDef`, and finally do have access both to parameter type variables and the annotation, we have already exited nested definitions which call the constraint solver without the benefit of the annotation.

We could solve this by further complicating the visitor with some stacks, but I think a refactor will make it easier to solve in a clean way and support #1073.
