### ISSUE TITLE
Impecise parse error location given

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/quint#465]
This module
```quint
module test {
    const possibleValues: Set[string]

    action step(v) = all {
        v.in(possibleValues)    
    }
}
```
 parses nicely.
However, the (presumably equivalent)
```quint
module test {
    const possibleValues: Set[string]

    action step(v) = all {
        v in possibleValues
    }
}
```
returns this error:

> error: extraneous input '(' expecting {'module', '}', 'const', 'var', 'assume', 'type', 'import', 'val', 'def', 'pure', 'action', 'run', 'temporal', DOCCOMMENT}

(referring to the `(` surrounding the argument `v` of the action `step`)

**Comment by shonfeder** [comment]
Thanks for the report!

I think the problem from a syntax perspective is that we do not support `in` as an infix operator. (Tho the language spec may not be up to date to reflect this. I'll check.)

However, we have another problem here clearly that the wrong location is being flagged as the source of the error. This may be due to an ambiguity in the grammar that gets triggered when it hits an invalid operator being used as infix.

**Comment by ivan-gavran** [comment]
I should have linked what made me thing it would be supported - I was reading from [here](https://github.com/informalsystems/quint/blob/f5db7e70839ca641eeb41c4cac0fe3ca59372c8c/doc/lang.md?plain=1#L1112).

Thanks for the response - feel free to close the issue if revamping of the `lang.md` document is underway, or keep it around to remind you of this obsolete part of it.
