### ISSUE TITLE
Mode checker loses track of parameters in nested definitions

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#567]
I am trying the following piece in the VSCode plugin:

```
    pure def foo(x: int): int = {
        pure val y = x + 1
        y
    }
```

The mode checker is complaining about the definition of `y`. On the other hand, the following surprisingly works:

```
    pure def foo(x: int): int = {
        val y = x + 1
        y
    }
```

Is it a bug, @bugarela?

**Comment by bugarela** [comment]
The first case not working is a bug. The second one should work fine, with a linter suggestion pointing out that you could add `pure` (but that won't happen right now since the modeChecker thinks the correct mode is `val`).

The problem is that the mode checker does not know that `x` is a parameter when it is looking inside the definition of `y`. I don't know how to solve this atm, I might have to rethink how we define effect variables for parameters at all.

Thanks for reporting :smile:

**Comment by bugarela** [comment]
This issue is blocking #646 since it breaks a lot of integration tests once we properly propagate temporal effects everywhere we should. Therefore, I'm prioritizing this.
