### ISSUE TITLE
Migrate github actions to Node 16

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#713]
As described here: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Our current actions started to fail, perhaps, due to the older version of node.

**Comment by bugarela** [comment]
Seems like we are actually using node 17 in CI. Seems like the link for the windows binary is broken: https://nodejs.org/dist/v17.9.1/win-x64/node.exe

**Comment by bugarela** [comment]
Ah, it's a bug on their side: https://github.com/nodejs/build/issues/3231
Shall we close this?

**Comment by konnov** [comment]
In the bottom of Github actions, e.g. https://github.com/informalsystems/quint/actions/runs/4451572805

![Screenshot 2023-03-20 at 10 50 03](https://user-images.githubusercontent.com/436810/226304120-c58ccf6f-8285-4cdd-a81e-1d680126def4.png)

**Comment by bugarela** [comment]
Ah, I didn't see that. Seems like we will have to update the actions we use from @v2 to @v3 and that might fix this.

> What you need to do
For Actions maintainers: Update your actions to run on Node 16 instead of Node 12 ([Actions configuration settings](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions))
For Actions users: Update your workflows with latest versions of the actions which runs on Node 16 ([Using versions for Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions))

From the [link](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) in the warnings

**Comment by thpani** [comment]
Related: #867
Probably makes sense to streamline versions between docs and CI.

**Comment by shonfeder** [comment]
This is resolved afaik!

**Comment by thpani** [comment]
Ah yes, I didn't know there was an issue. Fixed in #1171
